version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  # General
  all:
    desc: "Run all tasks"
    cmds:
      - task go:lint
      - task go:test
      - task go:fmt
      - task docker:lint
      - task api:lint
      - task actions:lint

  dev:
    desc: "Run development environment"
    cmds:
      - docker compose up --build

  build:
    desc: "Build Docker image"
    cmds:
      - docker build -t chronotes .

  dev:re:
    desc: "Rebuild service"
    cmds:
      - docker compose up -d --build --force-recreate {{.CLI_ARGS}}

  # Go
  go:lint:
    desc: "Lint Go code"
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go vet ./...
      - staticcheck ./...

  go:test:
    desc: "Run Go tests"
    cmds:
      - go build ./...
      - go test -v ./...

  go:fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...
      - go install golang.org/x/tools/cmd/goimports@latest
      - find . -print | grep --regex '.*\.go' | xargs goimports -w -local "github.com/yashikota/chronotes"

  # Docker
  docker:lint:
    desc: "Lint Dockerfile"
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile

  # API
  # api:ogen:
  #   desc: "Generate OpenAPI specification"
  #   cmds:
  #     - docker run --rm -v {{.PWD}}:/wd ghcr.io/ogen-go/ogen:v1.4.1 --target wd/pkg/ogen --clean wd/docs/api/bundled.yaml

  api:fmt:
    desc: "Format OpenAPI specification"
    cmds:
      - docker run --rm -v {{.PWD}}:/wd --workdir="/wd" -t --user $(id -u):$(id -g) azsdkengsys.azurecr.io/typespec format "**/*.tsp"

  api:lint:
    desc: "Lint API documentation"
    cmds:
      - task: api:tsp
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 lint --config docs/api/redoc.yaml docs/api/bundled.yaml

  api:tsp:
    desc: "Generate Open API from TypeSpec"
    cmds:
      - docker run --rm -v {{.PWD}}:/wd --workdir="/wd" -t --user $(id -u):$(id -g) azsdkengsys.azurecr.io/typespec compile docs/spec
      - task: api:split

  api:split:
    desc: "Split OpenAPI specification"
    cmds:
      - rm -rf docs/spec/components docs/spec/paths
      - docker run --rm -v {{.PWD}}:/spec --user $(id -u):$(id -g) redocly/cli:1.25.2 split docs/api/bundled.yaml --outDir=docs/api

  # api:bundle:
  #   desc: "Bundle OpenAPI specification"
  #   cmds:
  #     - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 bundle docs/api/openapi.yaml -o docs/api/bundled.yaml

  # GitHub Actions
  actions:lint:
    desc: "Lint GitHub Actions"
    cmds:
      - go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - actionlint

  # Markdown
  md:lint:
    desc: "Lint Markdown files"
    cmds:
      - docker run --rm -v {{.PWD}}:/wd -w /wd -t markdownlint/markdownlint:latest *.md docs/*.md
