// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddTagsToNote implements addTagsToNote operation.
//
// Add tags to a note.
//
// POST /api/v1/notes/{noteId}/tags
func (UnimplementedHandler) AddTagsToNote(ctx context.Context, req *AddTagsRequest, params AddTagsToNoteParams) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// ConnectService implements connectService operation.
//
// Connect to an external service.
//
// POST /api/v1/integrations/{service}/connect
func (UnimplementedHandler) ConnectService(ctx context.Context, params ConnectServiceParams) error {
	return ht.ErrNotImplemented
}

// CreateNote implements createNote operation.
//
// Create a new note.
//
// POST /api/v1/notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *CreateNoteRequest) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNote implements deleteNote operation.
//
// Delete a note.
//
// DELETE /api/v1/notes/{noteId}
func (UnimplementedHandler) DeleteNote(ctx context.Context, params DeleteNoteParams) error {
	return ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Delete a user.
//
// DELETE /api/v1/users/{userId}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) error {
	return ht.ErrNotImplemented
}

// DisconnectService implements disconnectService operation.
//
// Disconnect from an external service.
//
// DELETE /api/v1/integrations/{service}/disconnect
func (UnimplementedHandler) DisconnectService(ctx context.Context, params DisconnectServiceParams) error {
	return ht.ErrNotImplemented
}

// GetAllTags implements getAllTags operation.
//
// Get all tags.
//
// GET /api/v1/tags
func (UnimplementedHandler) GetAllTags(ctx context.Context) (r *GetAllTagsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDailySummary implements getDailySummary operation.
//
// Get daily note summary.
//
// GET /api/v1/analytics/daily
func (UnimplementedHandler) GetDailySummary(ctx context.Context) (r *NoteSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonthlySummary implements getMonthlySummary operation.
//
// Get monthly note summary.
//
// GET /api/v1/analytics/monthly
func (UnimplementedHandler) GetMonthlySummary(ctx context.Context) (r *NoteSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNote implements getNote operation.
//
// Get a specific note.
//
// GET /api/v1/notes/{noteId}
func (UnimplementedHandler) GetNote(ctx context.Context, params GetNoteParams) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNoteTemplates implements getNoteTemplates operation.
//
// Get note templates.
//
// GET /api/v1/note-templates
func (UnimplementedHandler) GetNoteTemplates(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNotes implements getNotes operation.
//
// Get a list of notes.
//
// GET /api/v1/notes
func (UnimplementedHandler) GetNotes(ctx context.Context, params GetNotesParams) (r *GetNotesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetQuarterlySummary implements getQuarterlySummary operation.
//
// Get quarterly note summary.
//
// GET /api/v1/analytics/quarterly
func (UnimplementedHandler) GetQuarterlySummary(ctx context.Context) (r *NoteSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServiceData implements getServiceData operation.
//
// Get data from a connected service.
//
// GET /api/v1/integrations/{service}/data
func (UnimplementedHandler) GetServiceData(ctx context.Context, params GetServiceDataParams) (r *IntegrationService, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTagAnalytics implements getTagAnalytics operation.
//
// Get tag usage analytics.
//
// GET /api/v1/analytics/tags
func (UnimplementedHandler) GetTagAnalytics(ctx context.Context) (r *GetTagAnalyticsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWeeklySummary implements getWeeklySummary operation.
//
// Get weekly note summary.
//
// GET /api/v1/analytics/weekly
func (UnimplementedHandler) GetWeeklySummary(ctx context.Context) (r *NoteSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetYearlySummary implements getYearlySummary operation.
//
// Get yearly note summary.
//
// GET /api/v1/analytics/yearly
func (UnimplementedHandler) GetYearlySummary(ctx context.Context) (r *NoteSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Check API health.
//
// GET /api/v1/health
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r string, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Login user.
//
// POST /api/v1/users/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r *RegisterUserResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Logout user.
//
// POST /api/v1/users/logout
func (UnimplementedHandler) Logout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// RegisterUser implements registerUser operation.
//
// Register a new user.
//
// POST /api/v1/users/register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserRequest) (r *RegisterUserResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveNoteDraft implements saveNoteDraft operation.
//
// Save a note as draft.
//
// POST /api/v1/notes/{noteId}/draft
func (UnimplementedHandler) SaveNoteDraft(ctx context.Context, params SaveNoteDraftParams) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchNotes implements searchNotes operation.
//
// Search notes.
//
// GET /api/v1/notes/search
func (UnimplementedHandler) SearchNotes(ctx context.Context, params SearchNotesParams) (r *SearchNotesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ShareNote implements shareNote operation.
//
// Share a note with another user.
//
// POST /api/v1/notes/{noteId}/share
func (UnimplementedHandler) ShareNote(ctx context.Context, req *ShareNoteRequest, params ShareNoteParams) error {
	return ht.ErrNotImplemented
}

// UnshareNote implements unshareNote operation.
//
// Unshare a previously shared note.
//
// DELETE /api/v1/notes/{noteId}/share
func (UnimplementedHandler) UnshareNote(ctx context.Context, params UnshareNoteParams) error {
	return ht.ErrNotImplemented
}

// UpdateNote implements updateNote operation.
//
// Update an existing note.
//
// PUT /api/v1/notes/{noteId}
func (UnimplementedHandler) UpdateNote(ctx context.Context, req *UpdateNoteRequest, params UpdateNoteParams) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadNoteImage implements uploadNoteImage operation.
//
// Upload an image to a note.
//
// POST /api/v1/notes/{noteId}/images
func (UnimplementedHandler) UploadNoteImage(ctx context.Context, req *UploadImageRequest, params UploadNoteImageParams) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
